// default package
// Generated 12-feb-2018 17:51:12 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cursos generated by hbm2java
 */
public class Cursos implements java.io.Serializable {

	private int curs;
	private Usuari usuari;
	private String descripcio;
	private Set<Usuari> usuaris = new HashSet<Usuari>(0);

	public Cursos() {
	}

	public Cursos(int curs) {
		this.curs = curs;
	}

	public Cursos(int curs, Usuari usuari, String descripcio, Set<Usuari> usuaris) {
		this.curs = curs;
		this.usuari = usuari;
		this.descripcio = descripcio;
		this.usuaris = usuaris;
	}

	public int getCurs() {
		return this.curs;
	}

	public void setCurs(int curs) {
		this.curs = curs;
	}

	public Usuari getUsuari() {
		return this.usuari;
	}

	public void setUsuari(Usuari usuari) {
		this.usuari = usuari;
	}

	public String getDescripcio() {
		return this.descripcio;
	}

	public void setDescripcio(String descripcio) {
		this.descripcio = descripcio;
	}

	public Set<Usuari> getUsuaris() {
		return this.usuaris;
	}

	public void setUsuaris(Set<Usuari> usuaris) {
		this.usuaris = usuaris;
	}

}
