// default package
// Generated 12-feb-2018 17:51:12 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Inscripcions generated by hbm2java
 */
public class Inscripcions implements java.io.Serializable {

	private Integer idInscripcio;
	private Usuari usuari;
	private Grupmoodle grupmoodle;
	private int tasquesPendents;
	private int tasquesAvaluades;
	private Date dataAltaInscripcio;
	private Date dataBaixaInscripcio;
	private boolean autoInscripcio;

	public Inscripcions() {
	}

	public Inscripcions(Usuari usuari, Grupmoodle grupmoodle, int tasquesPendents, int tasquesAvaluades,
			boolean autoInscripcio) {
		this.usuari = usuari;
		this.grupmoodle = grupmoodle;
		this.tasquesPendents = tasquesPendents;
		this.tasquesAvaluades = tasquesAvaluades;
		this.autoInscripcio = autoInscripcio;
	}

	public Inscripcions(Usuari usuari, Grupmoodle grupmoodle, int tasquesPendents, int tasquesAvaluades,
			Date dataAltaInscripcio, Date dataBaixaInscripcio, boolean autoInscripcio) {
		this.usuari = usuari;
		this.grupmoodle = grupmoodle;
		this.tasquesPendents = tasquesPendents;
		this.tasquesAvaluades = tasquesAvaluades;
		this.dataAltaInscripcio = dataAltaInscripcio;
		this.dataBaixaInscripcio = dataBaixaInscripcio;
		this.autoInscripcio = autoInscripcio;
	}

	public Integer getIdInscripcio() {
		return this.idInscripcio;
	}

	public void setIdInscripcio(Integer idInscripcio) {
		this.idInscripcio = idInscripcio;
	}

	public Usuari getUsuari() {
		return this.usuari;
	}

	public void setUsuari(Usuari usuari) {
		this.usuari = usuari;
	}

	public Grupmoodle getGrupmoodle() {
		return this.grupmoodle;
	}

	public void setGrupmoodle(Grupmoodle grupmoodle) {
		this.grupmoodle = grupmoodle;
	}

	public int getTasquesPendents() {
		return this.tasquesPendents;
	}

	public void setTasquesPendents(int tasquesPendents) {
		this.tasquesPendents = tasquesPendents;
	}

	public int getTasquesAvaluades() {
		return this.tasquesAvaluades;
	}

	public void setTasquesAvaluades(int tasquesAvaluades) {
		this.tasquesAvaluades = tasquesAvaluades;
	}

	public Date getDataAltaInscripcio() {
		return this.dataAltaInscripcio;
	}

	public void setDataAltaInscripcio(Date dataAltaInscripcio) {
		this.dataAltaInscripcio = dataAltaInscripcio;
	}

	public Date getDataBaixaInscripcio() {
		return this.dataBaixaInscripcio;
	}

	public void setDataBaixaInscripcio(Date dataBaixaInscripcio) {
		this.dataBaixaInscripcio = dataBaixaInscripcio;
	}

	public boolean isAutoInscripcio() {
		return this.autoInscripcio;
	}

	public void setAutoInscripcio(boolean autoInscripcio) {
		this.autoInscripcio = autoInscripcio;
	}

}
