// default package
// Generated 12-feb-2018 17:51:12 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuari generated by hbm2java
 */
public class Usuari implements java.io.Serializable {

	private Integer idUsuari;
	private Cursos cursos;
	private Tipususuari tipususuari;
	private String nomUsuari;
	private String cognom1usuari;
	private String cognom2usuari;
	private String dni;
	private String codiUsuari;
	private Boolean bloquejat;
	private Date dataAlta;
	private Date dataBaixa;
	private String password;
	private Set<Cursos> cursoses = new HashSet<Cursos>(0);
	private Set<Grupmoodle> grupmoodles = new HashSet<Grupmoodle>(0);
	private Set<Inscripcions> inscripcionses = new HashSet<Inscripcions>(0);

	public Usuari() {
	}

	public Usuari(Tipususuari tipususuari) {
		this.tipususuari = tipususuari;
	}

	public Usuari(Cursos cursos, Tipususuari tipususuari, String nomUsuari, String cognom1usuari, String cognom2usuari,
			String dni, String codiUsuari, Boolean bloquejat, Date dataAlta, Date dataBaixa, String password,
			Set<Cursos> cursoses, Set<Grupmoodle> grupmoodles, Set<Inscripcions> inscripcionses) {
		this.cursos = cursos;
		this.tipususuari = tipususuari;
		this.nomUsuari = nomUsuari;
		this.cognom1usuari = cognom1usuari;
		this.cognom2usuari = cognom2usuari;
		this.dni = dni;
		this.codiUsuari = codiUsuari;
		this.bloquejat = bloquejat;
		this.dataAlta = dataAlta;
		this.dataBaixa = dataBaixa;
		this.password = password;
		this.cursoses = cursoses;
		this.grupmoodles = grupmoodles;
		this.inscripcionses = inscripcionses;
	}

	public Integer getIdUsuari() {
		return this.idUsuari;
	}

	public void setIdUsuari(Integer idUsuari) {
		this.idUsuari = idUsuari;
	}

	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

	public Tipususuari getTipususuari() {
		return this.tipususuari;
	}

	public void setTipususuari(Tipususuari tipususuari) {
		this.tipususuari = tipususuari;
	}

	public String getNomUsuari() {
		return this.nomUsuari;
	}

	public void setNomUsuari(String nomUsuari) {
		this.nomUsuari = nomUsuari;
	}

	public String getCognom1usuari() {
		return this.cognom1usuari;
	}

	public void setCognom1usuari(String cognom1usuari) {
		this.cognom1usuari = cognom1usuari;
	}

	public String getCognom2usuari() {
		return this.cognom2usuari;
	}

	public void setCognom2usuari(String cognom2usuari) {
		this.cognom2usuari = cognom2usuari;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getCodiUsuari() {
		return this.codiUsuari;
	}

	public void setCodiUsuari(String codiUsuari) {
		this.codiUsuari = codiUsuari;
	}

	public Boolean getBloquejat() {
		return this.bloquejat;
	}

	public void setBloquejat(Boolean bloquejat) {
		this.bloquejat = bloquejat;
	}

	public Date getDataAlta() {
		return this.dataAlta;
	}

	public void setDataAlta(Date dataAlta) {
		this.dataAlta = dataAlta;
	}

	public Date getDataBaixa() {
		return this.dataBaixa;
	}

	public void setDataBaixa(Date dataBaixa) {
		this.dataBaixa = dataBaixa;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Cursos> getCursoses() {
		return this.cursoses;
	}

	public void setCursoses(Set<Cursos> cursoses) {
		this.cursoses = cursoses;
	}

	public Set<Grupmoodle> getGrupmoodles() {
		return this.grupmoodles;
	}

	public void setGrupmoodles(Set<Grupmoodle> grupmoodles) {
		this.grupmoodles = grupmoodles;
	}

	public Set<Inscripcions> getInscripcionses() {
		return this.inscripcionses;
	}

	public void setInscripcionses(Set<Inscripcions> inscripcionses) {
		this.inscripcionses = inscripcionses;
	}

}
